uab-cgds-worthey/rosalution

README.md
Signed-off-by: Angelina Uno-Antonison <ange.unoantonison@gmail.com>
:D
=> Fixed location of DNA emoji to after genetic variation

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, CONTRIBUTING.md
Wrike Ticket - [GitHub Issue Template Research](https://www.wrike.com/open.htm?id=1030798956)
Changes made:
- Updated the contributing guidelines
- Created bug report template
- Created feature-request template
**To Review:**
Make a to do list of things to check for to approve the pull request
=> Issue templates setup

.github/workflows/system-tests.yml, etc/etc-hosts.sh
[GitHub Actions run Automated System Testing](https://www.wrike.com/open.htm?id=1031110376)
- Added GitHub Workflow to run System Test actions for each commit.
**To Review:**
Make a to do list of things to check for to approve the pull request
=> Automated system tests GitHub actions

.github/pull_request_template.md
Wrike Ticket - [GitHub Pull Request Template Research](https://www.wrike.com/open.htm?id=1031068454)
Changes made:
- Added comments to make future pull request descriptions more concise.
**To Review:**
=> Pull request template edits

.gitignore, README.md, backend/README.md, setup.sh
Wrike Ticket - [Investigate setup.sh script creating a virtual python environment that could be used and update the documentation on using it](https://www.wrike.com/open.htm?id=1033377805)
setup.sh:
- A command is added to navigate to the backend directory
- A command is added to create a python virtual environment named `rosalution_env`
- A command is added to activate the virtual environment
- A command is added to install requirements.txt in the virtual environment
- A command is added to deactivate the virtual environment
- A command is added to navigate back to the root directory and continue the script.
README.md:
- updated the documentation to reflect the changes to the `setup.sh` script
gitignore:
- added the folder created for the venv to the gitignore
To check this run the …
=> Virtual python environment in setup

frontend/src/App.vue, frontend/src/components/AppFooter.vue, frontend/src/components/Footer.vue, frontend/src/main.js
Wrike Ticket - [On the frontned, add a tiny footer that credits CGDS developing Rosalution](https://www.wrike.com/open.htm?id=1033379957)
Changes made:
New component AppFooter.vue
- Created a new vue component named AppFooter
App.vue
- Added a new component, `AppFooter` inside the template and enclosed router-view inside a div 
main.js
- A new component `AppFooter` was imported from ./components/AppFooter.vue and registered as a component.
- The component `AppFooter` is added as a global component.
**To Review:**
=> Add a footer to the website that credits CGDS

README.md
Wrike Ticket - [README.md for production & login production between development & production](https://www.wrike.com/open.htm?id=1040328943)
Changes made:
- updated the documentation to include details about authentication and building for production and local production.
**To Review:**
=> Production documentation

.github/ISSUE_TEMPLATE/bug-report.yml, .github/workflows/system-tests.yml, README.md, backend/README.md, frontend/README.md, system-tests/support/commands.js
Wrike Task - [CGDS Team Members Practice Setting up for Development/Review of Rosalution](https://www.wrike.com/open.htm?id=1040360310) [Issue Title](Link to Issue here)
Changes made:
* Pre-requisites listed are no longer in a table but are in a  bulleted list that includes hyperlinks for installation/setup and some additional context
* Recommended setup for docker is 'Docker Desktop' and 'Docker Compose' with additional context and information about 'docker-compose' and 'docker compose'.  Documentation examples and codebase use 'docker compose' now instead to facilitate a simpler environment setup, but docker-compose still works.
* Updated the order of sections to place "Deployments" before "Testing".  This seems to be a more logical order for those reviewing and pairs better with …
=> Feedback revisions from cgds dev team number 1 fans

README.md, backend/Dockerfile, backend/etc/entrypoint-init.sh, backend/src/main.py, backend/src/routers/auth_router.py, backend/src/routers/dev_router.py, backend/tests/integration/test_auth_routers.py, backend/tests/integration/test_dev_routers.py, docker-compose.local-production.yml, docker-compose.production.yml, frontend/src/stores/authStore.js, system-tests/support/commands.js
Wrike Ticket - [Strip /loginDev endpoint from the production build](https://www.wrike.com/open.htm?id=1043120288)
Changes made:
- Added a ROSALUTION_ENV environment variable in the docker-compose.production.yml and docker-compose.local-production.yml
- This variable is set to `production`
- Added a dev_router.py
- Moved the `/auth/loginDev.py` to `/dev/loginDev`
- Updated the corresponding tests
- Updated the `entrypoint-init.sh` to add the DEBUG stripping if the ROSALUTION_ENV is set to `production`
- Updated the backend Dockerfile to remove the `dev_router.py` in production-stage
- Updated the README.md to reflect and describe the general changes made 
**To Review:**
``` bash
```
- Navigate to …
=> Development debug route

backend/README.md
Wrike Ticket - [CAS authentication configuration documentation for backend README](https://www.wrike.com/open.htm?id=1040344260)
Changes made:
- Updated the backend/README.md to explain the configurability of the CAS login system
**To Review:**
=> Backend cas auth writeup

README.md, backend/README.md, frontend/README.md
Wrike Ticker - [Additional context and information on the use of the python virtual environment in the backend readme](https://www.wrike.com/open.htm?id=1044771273)
Changes made:
- Added details on setting up/activating the Python Virtual Environment in Backend Readme
- Linked main Readme to Backend Readme for referring to Python Virtual Environment details
- Made formatting changes in Frontend Readme
- Refactored main Readme - Rosalution Description section
**To Review:**
=> Documentation updates

etc/database/remove-analysis.sh
This fixes a bug in the `./etc/database/remove-analysis.sh` script where some commands for mongo were missing variables and parameters were hard coded. This should now be all configurable.
Changes made:
- Updated the pedigree file remove to:
- Use the {docker_prefix}
- Use the mongo --host flag with the connections string variable
- Use the $database variable instead of hardcoding `rosalution_db`
- Change mongofiles to use --host and connection string and -d database variable
- Updated the supporting evidence files remove
- Use the {docker_prefix}
- Use the --host flag with connection_string
- Use the $database variable
- Have mongofiles use the --host connection string and -d database variable
**To Review:**
``` bash
docker-compose up …
```
=> More remove analysis script

etc/database/README.md, etc/database/backup-database.sh, etc/database/set-new-annotations-configuration.sh
Wrike Ticket - [Create a new database helping script to upload a new annotation configuration and backup the old](https://www.wrike.com/open.htm?id=1074585146)
Changes made:
- Created a new script to generate a backup of the annotations configuration and the upload and replace it with a new configuration for annotation.
**To Review:**
``` bash
```
- Make a valid change to the `./etc/fixtures/initial-seed/annotations-config.json`
- Open a terminal window and verify what the value is currently in the collection
```bash
docker exec -it rosalution-rosalution-db-1 mongosh rosalution_db
db.annotations_config.find()
```
- Run the script to create the backup of the current annotation configuration & upload the new …
=> Annotation configuration update scripts

etc/fixtures/import/C-PAM0042.json, etc/fixtures/import/C-PAM0044.json
Adding fixtures to the repository for CPAM0042 and CPAM0044.
[https://www.wrike.com/open.htm?id=1067971542](https://www.wrike.com/open.htm?id=1067971542)
Changes made:
- Separated the original consolidated upload of CPAM0042 and CPAM0044. The case has the same sample, but different genes/variants.
- C-PAM0042
- NM_004972.3(JAK2): c.1694G>C (p.Arg565Thr)
- CPAM0044
- NM_001230.4(CASP10): c.1030C>G (p.Pro344Ala)
**To Review:**
``` bash
```
- Go to: [http://local.rosalution.cgds/rosalution/](http://local.rosalution.cgds/rosalution/)
- Login with a user
- username: developer
- Click the "Create New Analysis" card
- Upload analysis:
- `etc/fixtures/import/C-PAM0042.json`
- `etc/fixtures/import/C-PAM0044.json`
- …
=> Added Cpam0042 and Cpam0044 analysis json to etc/fixtures/import

docker-compose.production.yml
[https://www.wrike.com/open.htm?id=1077637723](https://www.wrike.com/open.htm?id=1077637723)
Changes made:
- Updated the docker-compose.production.yml from GitLab to GitHub
**To Review:**
- Backup mongo rosalution_db:
``` bash
sudo docker ps # rosalution-db.1.l1sya363flu7wfe252izm610a
./backup-database.sh rosalution-db.1.l1sya363flu7wfe252izm610a /home/centos/backups/rosalution-db-backup  
```
- Docker stack deploy to prod
``` bash
export ROSALUTION_VERSION=0.6.0
cd /opt/rosalution
sudo -E docker stack deploy --prune --with-registry-auth --compose-file docker-compose.production.yml rosalution-prod
```
=> Updated docker-compose.production.yml to use github docker registry

README.md
Wrike Ticket - [Revise Rosalution prerequisite documentation to indicate which parts of Node.JS and Python  are needed](https://www.wrike.com/open.htm?id=1082255158)
Changes made:
- Updated the primary README to include more details on different aspects of the system dependencies for contributing to rosalution require.
- Node.JS & Yarn
- Python venv and pip3, and that sometimes, python venv isn't packaged with python? 
- Additional context for the need to be able for write access to /etc/hosts 
**To Review:**
=> Revise Rosalution prerequisite documentation to indicate which parts of Node.JS and Python  are needed

.github/workflows/common-static-analysis.yml, .github/workflows/nodejs.yml, .github/workflows/python.yml, .github/workflows/system-tests.yml
None - Being done directly due to feedback from GitHub support and to be able to run GitHub actions against pull request for 
Need to include the pull_request event trigger so that outside contributors can have GitHub Actions get approval to run in their pull request into Rosalution executed.
**To Review:**
=> Need to include the pull_request event trigger

.github/workflows/build-and-publish-docker-images.yml, .github/workflows/development-main-deployment.yml
Wrike Ticket - [Automated Rosalution development deployments from GitHub main of a production build of Rosalution](https://www.wrike.com/open.htm?id=1082290217)
A supplement pull request will be made to the GitLab repository with CGDS DevOps cluster updates to deploy the self-hosted GitHub Runners in ansible. https://gitlab.rc.uab.edu/center-for-computational-genomics-and-data-science/devops/cgds-devops-cluster/-/merge_requests/24
Changes made:
- New workflow to automatically deploy a production build of Rosalution to the CGDS DevOps cluster utilizing self-hosted GitHub Runners
-  Relies on the "Compile & Publish" Workflow to complete as a trigger to execute this workflow.  It also has workflow dispatch as an option to run it manually.
- Created a new GitHub Repository Variable for …
=> Deploy prod build to devops cluster

README.md
Request from Liz
Changes made:
- Restructuring the acknowledgments section
**To Review:**
=> Updated the acks section

frontend/src/components/Dialogs/Toast.vue, frontend/src/models/annotations.js, frontend/src/toast.js, frontend/src/views/AnalysisView.vue, frontend/test/components/Dialogs/Toast.spec.js
Wrike Ticket - [Toast messages component development](https://www.wrike.com/open.htm?id=1107661424)
Changes made:
- Created a new Toast component to visualize notifications that will disappear after 3 seconds.
- Included making updates to unit tests to prevent warnings that came propped up
**To Review:**
1.  Update the `./frontend/src/views/AnalysisListingView.vue` to include the Toast component for uploading a case successfully. It is implemented like the Notification and Input dialogs.  To use the toast message box, use either 
```javascript
toast.error('message here');
toast.info('message here');
toast.success('message here');
```
3. Deploy Rosalution
``` bash
```
4. Go to: …
=> Toast all the way

backend/requirements.txt
[As a developer, investigate why backend container is using a lot of resources constantly to ensure it does not cause problems in production](https://www.wrike.com/open.htm?id=1096855511)
Changes made:
- Updated the `backend/requirements.txt` uvicorn package:
- `uvicorn==0.20.0` -> `uvicorn[standard]==0.22.0` to include `watchfiles` for reloading as per the [uvicorn documentation](https://www.uvicorn.org/settings/#development)
**To Review:**
- Bonus: Check main branch CPU usage then switch to the new branch to check the CPU usage
``` bash
docker exec -it rosalution-backend-1 bash
top
```
- Look at the usage, is it negligible?
- Make a change in the backend and save it (perhaps a print statement somewhere)
- …
=> As a developer, investigate why backend container is using a lot of resources

backend/src/security/security.py, backend/tests/unit/security/test_security.py, frontend/src/main.js, frontend/src/stores/authStore.js, frontend/src/views/AccountView.vue, frontend/src/views/AnalysisListingView.vue, frontend/src/views/AnalysisView.vue, frontend/test/stores/authStore.spec.js
The application will now redirect the user properly to the login screen if their Oauth token is no longer valid. This is done by trying to verify an existing token and if it fails to validate, the backend will delete the existing token and the app will redirect to the login page.
Also, the front end will clear the state of the authStore if a logout occurs or an invalid token occurs.
[Wrike: Properly redirect the user to the login page if the system gets updated](https://www.wrike.com/open.htm?id=1092890477)
Changes made:
- Describe changes you made in bullet points
**To Review:**
``` bash
```
- Visit [http://local.rosalution.cgds/rosalution](http://local.rosalution.cg …
=> Properly redirect the user to the login page if the system gets updated

backend/tests/integration/test_analysis_routers.py, backend/tests/unit/repository/test_analysis_collection.py, etc/fixtures/initial-seed/analyses.json, system-tests/e2e/rosalution_analysis.cy.js, system-tests/e2e/rosalution_home.cy.js
[system test for status in header](https://www.wrike.com/open.htm?id=1109305485)
Changes made:
- Modified the fixture for seeding to start with a case in the annotation state
- Added a test for checking that the status icon updates in the header when it changes state
**To Review:**
To run the system tests, you need to have rosalution running locally in a docker container.
1. Deploy Rosalution
``` bash
```
Once you have rosalution running, you can run the system tests by running the following command:
2. Run Tests
```bash
cd system-tests
yarn test:e2e
```
=> Sys test status in header

README.md
None - JOSS review has been initiated
https://github.com/openjournals/joss-reviews/issues/5443 
Changes made:
- Added the Status Badge for Rosalutions JOSS review
**To Review:**
=> Adding JOSS journal review tag for rosalution

frontend/src/components/AnnotationView/AnnotationSidebar.vue, frontend/src/models/analyses.js, frontend/src/views/AnnotationView.vue, frontend/test/views/AnnotationView.spec.js, system-tests/e2e/case_annotation_section_anchors.cy.js, system-tests/e2e/upload_images_to_case_annotations.cy.js
Wrike Task: [Update the annotation rendering configuration to include additional sections that are within presentations as of Spring 2023](https://www.wrike.com/open.htm?id=1111989420)
Changes made:
- Refactored and added additional sections to the annotation view
- Added additional CSS styling to the sidebar 
- have it be fixed with of 12.5rem
- have it have a scroll bar when unable to view all of the buttons on one page due to screen/window size
- Updated system tests
- Updated unit tests
- Refactored the logic for replacing the '_' in the sidebar anchor menu buttons on the annotation view
- moved the different model systems to their respective models
**To Review:**
1.   Deploy Rosalution
``` bash
``` 
2. …
=> annotation rendering configuration frontend updates

frontend/src/components/Dialogs/InputDialog.vue, frontend/src/components/Dialogs/InputDialogUploadFile.vue, frontend/src/inputDialog.js, frontend/src/views/AnalysisListingView.vue, frontend/test/components/Dialogs/InputDialog.spec.js
Wrike Task - [As an <authorized user>, I want the case import dialog to indicate that the application is not safe to contain PHI information so that I can ensure that sensitive patient information is not accidentally uploaded and remains protected.](https://www.wrike.com/open.htm?id=1079628801)
Changes made:
- Added a new option for input dialogs called warningText
- Updated the style of the input dialog
- Changed the size of the drag-and-drop box for file upload
- Added additional unit tests for the new warningText property of the input dialog
**To Review:**
1.   Deploy Rosalution
``` bash
``` 
2. Go to: [http://local.rosalution.cgds/rosalution/](http://local.rosalution.cgds/rosalution/)
3. Login with a …
=> Case input phi warning

backend/tests/integration/test_analysis_routers.py, backend/tests/unit/core/test_annotate.py, backend/tests/unit/repository/test_annotation_collection.py, etc/fixtures/initial-seed/annotations-config.json, etc/fixtures/initial-seed/genomic-units.json, frontend/src/components/AnnotationView/AllianceGenomeCard.vue, frontend/src/components/AnnotationView/CardDataset.vue, frontend/src/main.js, frontend/src/models/analyses.js, frontend/src/views/AnnotationView.vue, frontend/test/components/AnnotationView/AllianceGenomeCard.spec.js, frontend/test/components/AnnotationView/CardDataset.spec.js, frontend/test/views/AnnotationView.spec.js, system-tests/e2e/case_annotation_section_anchors.cy.js
This PR intends to consolidate the updates to annotations for visualization the existing animal models from alliance genomic for each target animal model and the new figure annotation configurations for the annotations section.
**To Review:**
``` bash
docker compose up
```
=> Alliance genome models into new configuration

.github/workflows/build-and-publish-docker-images.yml, .github/workflows/common-static-analysis.yml, .github/workflows/draft-paper.yml, .github/workflows/nodejs.yml, .github/workflows/python.yml, .github/workflows/system-tests.yml
This is a PR to pair with us removing workflow jobs running twice for Push's and PR's.
https://github.com/uab-cgds-worthey/rosalution/pull/97
=> PR-CI/CD experiment status

backend/src/core/annotation_task.py, etc/api/annotate-all-existing-analyses.sh, etc/fixtures/initial-seed/annotations-config.json, etc/fixtures/remove-automatic-annotations.js
Added two scripts for expanded Rosalution functionality:
**remove-automatic-annotations.js**
- This script directly accesses a mongo database and strips all annotations from the existing genomic units that are not manually added by the user
**api/annotate-all-existing-analyses.sh**
- This script utilizes the existing endpoints and queues annotation jobs for all existing analyses in rosalution.
- Requires inputting the user's Client_Id and Client_Secret from their account page
[https://www.wrike.com/open.htm?id=1149581742](https://www.wrike.com/open.htm?id=1149581742)
Changes made:
- Also fixed the `etc/fixtures/initial-seed/annotations-config.json` as it was crashing annotations due to improper format of the  'forge' tasks.
**To Review:**
``` bash
docker system prune …
```
=> As a Developer, provide a way to remove all automatic annotations from analyses, so they can be re-annotated with the correct information

README.md
Issue Number 105 - [https://github.com/uab-cgds-worthey/rosalution/issues/105#issue-1794459958]
Changes made:
- Documentation on how to visit the application in the browser after deployment
- Addition troubleshooting deployment section
**To Review:**
=> Updated the README to discuss how to visit the locally deployed application

README.md
Changes made:
- Updating the main readme for the revised list of maintainers
**To Review:**
=> Updated the list of maintainers in the main repo readme.

backend/Dockerfile
[https://www.wrike.com/open.htm?id=1171066687](https://www.wrike.com/open.htm?id=1171066687)
Changes made:
This Pull Request fixes the issue with the production backend failing to load the logging.conf file as it doesn't exist in the image.
**To Review:**
``` bash
docker-compose -f docker-compose.local-production.yml up --build 
```
- Does the backend crash? (It shouldn't)
=> Backend production logging.conf

etc/fixtures/update-genomic-units-fixtures.sh
[https://www.wrike.com/open.htm?id=1169559580](https://www.wrike.com/open.htm?id=1169559580)
Changes made:
Added a script: `./etc/fixtures/update-genomic-units-fixtures.sh`
This script automatically exports an existing genomic_units collection from mongodb and saves it as a fixture Rosalution so it can be deployed with the updated info in the future.
**To Review:**
``` bash
```
- Login to Rosalution: `local.rosalution.cgds/rosalution` with the `developer` username
- Click on the `Developer` username on the dashboard and generate/show a secret key
- [Optional]: Ensure that the animal model urls don't exist in the existing fixtures:
- This is shown in a screenshot …
=> Genomic unit fixture updater

frontend/src/components/AnnotationView/ScoreDataset.vue, frontend/src/models/analyses.js, system-tests/e2e/case_annotation_visualize_score.cy.js
Wrike Ticket - [Ditto Score Frontend Component](https://www.wrike.com/open.htm?id=1175092123)
Changes made:
- Added DITTO configuration in analyses.js
- Corrected the typos in ScoreDataset.vue and analyses.js to get the correct color styles for the component
**To Review:**
``` bash
docker compose up --build -d 
```
- In `./frontend/src/views/AnnotationView.vue`
- Scroll below to the following method to append dummy data for DITTO to annotations
``` javascript
async getAnnotations() {
this.annotations =
{
...await Annotations.getAnnotations(
this.analysis_name, this.active.gene, this.activeVariantWithRemovedProtein,
),
...{
DITTO: 0.6,
},
};
},
```
- Go to …
=> DITTO Frontend Dataset Configuration

backend/src/routers/analysis_router.py, backend/src/routers/annotation_router.py, backend/src/routers/auth_router.py, backend/src/security/security.py, backend/tests/integration/test_analysis_routers.py, etc/fixtures/initial-seed/users.json
Wrike Ticket - [User Roles - Actively lock down endpoints as per the proper user roles](https://www.wrike.com/open.htm?id=980754351)
Changes made:
- Locked down backend endpoints for users with write scope
- Worked with @JmScherer on this
**To Review:**
=> Backend security lockdown

backend/src/routers/analysis_router.py, backend/src/routers/annotation_router.py, backend/src/routers/auth_router.py, backend/src/security/security.py, backend/tests/integration/test_analysis_routers.py, etc/fixtures/initial-seed/users.json, etc/fixtures/migrations/migrate-to-streamlined-user-scopes.js, frontend/src/components/AnalysisView/SectionBox.vue, frontend/src/components/AnnotationView/AnnotationSection.vue, frontend/src/stores/authStore.js, frontend/src/views/AnalysisListingView.vue, frontend/src/views/AnalysisView.vue, frontend/src/views/AnnotationView.vue, frontend/test/views/AnalysisListingView.spec.js, frontend/test/views/AnalysisView.spec.js, system-tests/e2e/attach_analysis_section_image.cy.js, system-tests/e2e/login_logout_combined.cy.js, system-tests/e2e/upload_images_to_case_annotations.cy.js, system-tests/support/commands.js, system-tests/support/e2e.js
Wrike Ticket - [Frontend-user roles securing](https://www.wrike.com/open.htm?id=1175899238)
Changes made:
- Updates to components to rely on user scopes for read/write permissions to allow updates
- API endpoints secured to rely on a user's scope to allow read/write operations
**To Review:**
1. Download the archived production database to your local machine.  See @SeriousHorncat for the URL to download it from Box.
2. Import the production database backup to Rosalution from the rosalution root directory
```bash
./etc/database/restore-database.sh rosalution-rosalution-db-1 rosalution-db-2023-07-07-1688746774.archive
```
3. Update User Roles from restored production database
```bash
docker exec rosalution-rosalution-db-1 mongosh …
```
=> Frontend-user roles securing

README.md
No ticket made - just making quick revision to the primary readme
Changes made:
- Updated the list of available users for logging in for local development
**To Review:**
=> Updated the local development user accounts available to test login with

CHANGELOG.md, README.md, build.sh, docker-compose.local-production.yml, docker-compose.yml, frontend/Dockerfile, frontend/index.html, frontend/package.json, frontend/yarn.lock
Changes made:
- Created a new CHANGELOG to track updates more clearly as they are associated with versions
- Documentation to communicate how to deploy docker images built using the `./build.sh` script
- Updated the build.sh script to include the "**VERSION_BUILD_TAG**" as a Docker build arg to all of the built containers so that if they need the current build version at build time, it is available
- docker-compose yaml file updates for local deployment, local production, and production deployments updated to include the new **VERSION_BUILD_TAG** build arg and its usage
- Frontend service uses the **VERSION_BUILD_TAG** arg to set the **VITE_ROSALUTION_VERSION** environment variable to set the version tag in the title of the page header
- Upgraded the Vite build to latest along with test …
=> GitHub Version Tag to set Version within Rosalution and Changelog

etc/fixtures/initial-seed/analyses.json, etc/fixtures/migrations/migrate-insert-animal-model-systems.js
[Script to add animal model to an Analysis as a Section in Rosalution](https://www.wrike.com/open.htm?id=1233368830)
Changes made:
- Script to add a new "Animal Model System" section into an analysis
- Has a variable to specify animal model header
- Has a variable to choose which analysis to insert
- Add fixture for an animal model system example in CPAM0002 for mouse
**To Review:**
``` bash
```
- Open a browser, go to [http://local.rosalution.cgds/rosalution](http://local.rosalution.cgds/rosalution)
- Click on CPAM0002 analysis card
- Is there a `Mus musculus (Mouse) Model System` section below `Clinical History`?
``` bash
docker ps
docker …
```
=> Script to add animal model to an Analysis as a Section in Rosalution

.github/workflows/system-tests.yml, .gitignore, README.md, docker-compose.yml, etc/generate-ssl-certs.sh, etc/traefik/config.yml, frontend/src/components/AnalysisView/GeneBox.vue, frontend/src/views/AnalysisView.vue, frontend/test/components/AnalysisView/GeneBox.spec.js, frontend/test/views/AnalysisView.spec.js, setup.sh, system-tests/cypress.config.js, system-tests/e2e/rosalution_analysis.cy.js
[https://www.wrike.com/open.htm?id=1246130628](https://www.wrike.com/open.htm?id=1246130628)
Changes made:
Adds HTTPS functionality to the local deployment of Rosalution. HTTPS allows for expanded features to be used within browsers, such as copying text to the operating system's clipboard. The clipboard functionality is now working for the frontend and includes corresponding unit tests and system tests. The existing clipboard button has been expanded with reactive elements such as changing color of the icon when clicking, changing the pointer to notify the user the button is interactive, and displaying a toast when the action is successful.
The HTTPS project structure follows the dev_prototype project: [https://github.com/uab-cgds-worthey/dev_prototype.git](https://github.com/uab-cgds-wor …
=> Implement HTTPS in Rosalution, complete with copying and system test

etc/fixtures/initial-seed/annotations-config.json
Wrike Ticket - [As a developer, I want to update Annotation Configuration to include data source versions to inform annotated datasets with versions](https://www.wrike.com/open.htm?id=1234983414)
Changes made:
- Updated Annotation Configuration with Versioning Details for the 4 different data sources - HPO, Ensembl, Alliance Genome and Rosalution
- Depending on type of versioning needed for datasource (`date`, `rest` or `rosalution`) added 1-3 versioning details fields for all datasets. 
**To Review:**
=> Updating Annotations configuration with Versioning Details

etc/fixtures/migrations/migrate-insert-discussion-and-supporting-keys.js
[https://www.wrike.com/open.htm?id=1206942859](https://www.wrike.com/open.htm?id=1206942859)
Changes made:
- Mongo migration script to update an analysis document to include `discussions` and `supporting_evidence_files` keys
**To Review:**
- Download a backed up mongo database: [rosalution-db-2023-12-12-1702397460](https://uab.box.com/s/d1hhlfx4y5dwh42gi51egd75dyqv3y23)
- Deploy Rosalution locally and restore the database backup
``` bash
./etc/database/restore-database.sh rosalution-rosalution-db-1 <path_to_mongo_backup>/rosalution-db-2023-12-12-1702397460.archive
Example:
./etc/database/restore-database.sh rosalution-rosalution-db-1 /Users/jscherer/Downloads/rosalution-db-2023-12-12-1702397460.archive
```
``` …
```
=> [Mongo] Create a migration script to update all existing analyses to include the discussion post structure

backend/src/core/annotation.py, backend/src/core/annotation_unit.py, backend/tests/unit/core/test_annotate.py, backend/tests/unit/core/test_annotation_unit.py
Wrike ticket - [Refactoring Backend, creating the AnnotationUnit class](https://www.wrike.com/open.htm?id=1267900215)
Changes made:
- Created `AnnotationUnit` class, to contain the annotating genomic-unit, and corresponding dataset.
- Refactored `annotation.py`, for the annotation queue to hold annotation units, and process tasks to process the annotation units.
- Updated tests for the refactor
**To Review:**
``` bash
```
- Navigate to [https://local.rosalution.cgds/rosalution/login](https://local.rosalution.cgds/rosalution/login)
- Login as `developer`. Click on any CPAM case, navigate to its Annotation view and ensure annotations are loading. Here is CPAM0083 as an example:
``` bash
cd backend
source …
```
=> Refactoring backend, creating AnnotationUnit class

backend/src/config.py, backend/src/main.py
[https://www.wrike.com/open.htm?id=1335131375](https://www.wrike.com/open.htm?id=1335131375)
Changes made:
- Updated the CORS policy on FastAPI to allow for configuration
**To Review:**
=> Update the CORS policy on FastAPI to allow for configuration

backend/requirements.txt, docs/prototypes/csv-to-table-prototype/package.json, docs/prototypes/fast-api-prototype/Requirements.txt, frontend/package.json, frontend/yarn.lock
Version audit for packages
Changes made:
- Package updates for minor versions for python-multipart, vitejs, and fastapi
**To Review:**
=> Packge version audit

backend/src/core/annotation.py, backend/src/core/annotation_task.py, backend/src/core/annotation_unit.py, system-tests/e2e/rosalution_analysis.cy.js, system-tests/package.json, system-tests/yarn.lock
Wrike ticket - [Get latest version of the dataset within the annotation unit](https://www.wrike.com/open.htm?id=1332529462)
Wrike Ticket - [Refactor annotation units to also have version as variable](https://www.wrike.com/open.htm?id=1332532048)
Changes made:
- Refactored AnnotationUnit class to have versions, and handle some of the versioning code that will go in in the future
- Created VersionAnnotationTask in `annotation_task`, as an Annotation Task type. This will be the task that will handle querying and retrieving the versions for annotation units, that are added to the queue to be processed.
- Modified `process_tasks` to check if version exists and if the version is latest. This code can be further changed as we add more work on this feature.
**To Review:**
To check this run the …
=> Annotation versioning part 2

backend/src/core/annotation.py, backend/src/core/annotation_unit.py, backend/tests/unit/core/test_annotation_unit.py
Wrike ticket - [Refactoring process_tasks function for annotation versioning](https://www.wrike.com/open.htm?id=1359254457)
Changes made:
- Refactored Annotation service's `process_tasks()` method to reduce nested statements. This issue was noticed when working on this [PR.](https://github.com/uab-cgds-worthey/rosalution/pull/170)
- Created two different functions in `annotation_unit.py` to handle the code to check if the annotation unit is `ready_for_annotation.py` and if it `should_continue_annotation.py`
- Added unit tests for these methods.
**To Review:**
``` bash
```
Navigate to [https://local.rosalution.cgds/rosalution/login](https://local.rosalution.cgds/rosalu …
=> Annotation process tasks refactor

backend/requirements.txt, backend/src/security/security.py, backend/tests/unit/security/test_security.py, frontend/package.json
Wrike Ticket - [Resolve reported Rosalution package vulnerabilities in frontend & backend](https://www.wrike.com/open.htm?id=1419198860)
Changes made:
- @JmScherer Replaced `python-jose` obe package that contains vulnerabilities and that is no longer maintained with PyJWT for JWT in Auth
- @SeriousHorncat Upgraded requests package in backend and force 'braces' to be 3.0.0 in package.json for frontend
Systems and tests pass;
**To Review:**
=> Investigate resolving package vulnerabilities - either by replacing or upgrading

backend/src/core/annotation.py, backend/src/core/dataset_manifest.py, backend/src/repository/analysis_collection.py, backend/src/repository/genomic_unit_collection.py, backend/src/routers/analysis_annotation_router.py, backend/src/routers/analysis_router.py, backend/src/routers/annotation_router.py, backend/tests/fixtures/analysis-CPAM0002.json, backend/tests/fixtures/annotations-NM001017980_3_c_164G_T.json, backend/tests/fixtures/annotations-VMA21.json, backend/tests/integration/test_analysis_annotation_routers.py, backend/tests/integration/test_analysis_routers.py, backend/tests/unit/conftest.py, backend/tests/unit/core/test_annotation_task.py, backend/tests/unit/repository/test_genomic_unit_collection.py, etc/fixtures/create-annotation-manifest.js, etc/fixtures/initial-seed/analyses.json, etc/fixtures/initial-seed/genomic-units.json, frontend/src/models/annotations.js
Wrike Ticket - [Update Dependencies to Use the analysis' dataset manifest to get the dataset's source & version, to see if exists](https://www.wrike.com/open.htm?id=1489650455)
Wrike Ticket - [Update getting Annotations to rely on the analysis' dataset manifest to get annotations for gene and hgvsvariants](https://www.wrike.com/open.htm?id=1489651648)
Changes made:
- Needed to part of the following ticket in order to accomplish the first ticket.
**To Review:**
=> Retrieve and show annotations

backend/src/models/analysis.py, backend/src/repository/analysis_collection.py, backend/src/routers/analysis_discussion_router.py, backend/tests/fixtures/analysis-CPAM0002.json, backend/tests/integration/test_analysis_discussion_routers.py, etc/fixtures/initial-seed/analyses.json, frontend/src/components/AnalysisView/AttachmentsSection.vue, frontend/src/components/AnalysisView/DiscussionAttachment.vue, frontend/src/components/AnalysisView/DiscussionPost.vue, frontend/src/components/AnalysisView/DiscussionReply.vue, frontend/src/components/AnalysisView/DiscussionSection.vue, frontend/src/components/Dialogs/InputDialogExistingAttachments.vue, frontend/src/main.js, frontend/src/models/analyses.js, frontend/src/stores/analysisStore.js, frontend/src/views/AnalysisView.vue, frontend/test/components/AnalysisView/DiscussionPost.spec.js, frontend/test/components/AnalysisView/DiscussionReply.spec.js, frontend/test/components/AnalysisView/DiscussionSection.spec.js, system-tests/README.md, system-tests/e2e/case_supporting_evidence.cy.js
Wrike Ticket - [As a collaborator, I would like to be able to reply to discussions so I can have a relevant conversation with other experts to make more robust decisions on an analysis](https://www.wrike.com/open.htm?id=1206935001)
Changes made:
- Added new feature 'Threading' to enable users to reply to published Discussion Posts, using Discussion Replies.
- Users should be able to add, edit and delete their replies.
- Updated fixtures to include sample discussion replies from Developer and Researcher users. Also added attachments in fixtures.
- Made minor addition to System Tests Documentation to include instructions to watch system tests in browser.
- Added unit tests in the frontend and integration tests in the backend to ensure threading is working ✨ 
**To Review:**
To check this run …
=> Threading: Discussion Replies

.github/pull_request_template.md
Changes made:
- Updated the Pull Request Template to include an update the CHANGELOG with any new work that goes in.
- 
**To Review:**
=> CHANGELOG note in Pull Request update
