uab-cgds-worthey/rosalution

backend/src/config.py
Wrike Ticket - [Improve the Rosalution API startup error message when validation fails to find the required "ROSALUTION_KEY" environment variable](https://www.wrike.com/open.htm?id=1033376951)
Changes made:
* Updated the backend API to validate if the ROSALUTION_KEY is provided.  If not, a value error is returned with a more descriptive message of the failure explaining that it is trying to read it from an Environment variable that is not sent.
**To Review:**
1.  Open the `docker-compose.yml` and comment out line 49 that contains setting the `ROSALUTION_KEY` environment variable.  this will ensure that the value is not being set in the container.
2. Deploy Rosalution and wait for it to completely startup
``` bash
``` …
=> Updated the validation of the application settings for more intuitive validation failure

.github/workflows/system-tests.yml, README.md, backend/Dockerfile, docker-compose.yml, setup.sh
Wrike Ticket - [Remove ROSALUTION_KEY from local development environment depdency](https://www.wrike.com/open.htm?id=1046455694)
Changes made:
Removed Rosalution's local deployment relying on modifications to the local development environment in a Bash shell's `~/.bashrc`.  This caused many problems for folks trying to try out deploying the application locally and adds additional complication to support the user of other shell envrionments. Newer versions of macosx use Z shell instead of Bash.
- Removed the environment key set in the system tests environment in the github actions workflow
- Updated primary README documentation removing reference to the ROSALUTION_KEY
- Updated local docker compose yml to not include the ROSALUTION_KEY and set the entrypoint for the backend to be the …
=> Remove ROSALUTION_KEY from local development environment depdency

backend/etc/entrypoint-init.sh, docker-compose.yml
Wrike Ticket - [Fix hot-reloading backend service with rosalution_key/entrypoint changes done](https://www.wrike.com/open.htm?id=1046455694)
Changes made:
Updated the backend entrypoint-init.sh script used to start the application and generate the rosalution_key inside the docker container at startup.  Forgot to add in the script to apply to expand the positional arguments provided to it to forward setting the backend service to hot-reload changes it observes to speed up development.
**To Review:**
``` bash
docker compose up --build backend
```
=> Adding positional argument expansion to forward entrypoint arguments to backend uvicorn executable

backend/src/core/annotation_task.py, backend/tests/unit/core/test_annotation_task.py, etc/fixtures/initial-seed/annotations-config.json, setup.sh
Wrike Ticket - [Investigate why annotation is halting halfway for a new sample](https://www.wrike.com/open.htm?id=1047573962)
Upon investigating why annotations were halting halfway, I discovered that an exception being thrown from an invalid 'jq' query occurring. A failure in extracting the annotation from 'jq' ought to not cause the entire threadpool to crash and halt annotations.  Since there were plenty of annotations left on the queue, most of the remaining annotations would run when another case was added to the application.
Also, discovered the annotation in question causing the issue is the "Entrez Gene Id" that is being queried from a gene symbol for HPO.  HPO released a new version of their API in place of their old one, causing the failure to occur.  Updated the base fixtures …
=> Resolving why annotation is halting halfway for a new sample

backend/src/models/analysis.py, backend/src/repository/analysis_collection.py, frontend/src/components/AnalysisListing/AnalysisCard.vue, frontend/src/components/DropDownMenu.vue, frontend/src/views/AnalysisListingView.vue, frontend/test/components/AnalysisListing/AnalysisCard.spec.js
Wrike Ticket - [Revise the Analysis card on the Rosalution main page to group a gene and related variants visually](https://www.wrike.com/open.htm?id=1067982940)
- Refactored and simplified the analysis summary API endpoint used for the cards to to reflect the updated grouping
- Restructured the cards to group a gene with variants visually, and visually identifying each variant in a light grey pill shape.
- Reloads the analyses summary cards when a sucessful import
**To Review:**
1.
``` bash
docker compose up
```
2. Visit http://local.rosalution.cgds/rosalution/
3. Login as 'user01'
4. Analysis cards look like screenshot below
5. Import a new analysis, these can be found in ./etc/fixtures/import
6. Does it immediately show up?
=> Refactored analysis summaries for grouping genomic units more clearly

frontend/src/components/AccountView/CredentialsBox.vue, frontend/src/components/AnalysisView/SectionBox.vue, frontend/src/views/AccountView.vue, frontend/test/components/AccountView/CredentialsBox.spec.js, frontend/test/views/AccountView.spec.js
- [The Generate Secret button will call the endpoint that generates the client_secret key and unhide it for the user](https://www.wrike.com/open.htm?id=1040376425)
Changes made:
- Created a new vue component called CredentialsBox.vue
- Created a new component test to test the CredentialsBox component.
- Refactored AccountView to make use of the new CredentialsBox Component.
- Refactored AccountView Unit Tests to account for the refactoring of AccountVue.
**To Review:**
``` bash
```
- Navigate to [local.rosalution.cgds/rosalution](local.rosalution.cgds/rosalution)
- login as a user
- Click on the username in the header to go to the account view
-  Verify that the Client ID is shown in the credentials box
- …
=> Account view-CredentialsBox component

frontend/src/components/DropDownMenu.vue, frontend/src/models/analyses.js, frontend/src/views/AnalysisView.vue, frontend/test/models/analyses.spec.js, frontend/test/views/AnalysisView.spec.js
Issue Number 53 - [Enable Users to update an analysis' status to Ready or Active](https://github.com/uab-cgds-worthey/rosalution/issues/53)
Changes made:
- Added Mark Ready and Mark Active with a conditional based on the status
- Created placeholder for Mark Active, because I observed the endpoint did not exist
- Created tests for AnalysisView and AnalysesModel
**To Review:**
- Deploy application
```bash
docker compose up
```
- Visit http://local.rosalution.cgds/rosalution/
- Login as 'user01'
- Import a new analysis, these can be found in ./etc/fixtures/import
- Click uploaded analysis and mark as ready
- Go back to home page to see state changed
- Return to analysis to see Mark Active action
=> Added Mark Ready and Mark Active conditions to analysis actions

backend/src/repository/analysis_collection.py, frontend/src/components/AnalysisListing/AnalysisCard.vue, frontend/src/views/AnalysisListingView.vue, frontend/test/components/AnalysisListing/AnalysisCard.spec.js
[Analysis summary page](https://www.wrike.com/open.htm?id=1089167230)
Changes made:
- Added logic to display third-party logos and link out in new tabs if there is a third-party link attached to the analysis
**To Review:**
- start from a clean development installation of Rosalution and login as a user
``` bash
```
- Navigate to [local.rosalution.cgds/rosalution](local.rosalution.cgds/rosalution)
- Login as a user
- Click on any Analysis Card.
- in the Analysis view hover over the vertical 3 dot menu and then click on Attach Monday.com
- Observe that a link modal opens up for you to input a link.
- Input any text/link and click Add
- Navigate back to the home page
- Observer that the monday.com logo now …
=> Third party logo link on summary cards

frontend/src/components/Dialogs/InputDialogAttachUrl.vue, frontend/src/components/Dialogs/InputDialogUploadFile.vue
[Bug Fix: Input Dialog Box File Input Drag & Drop Area is too small height in height](https://www.wrike.com/open.htm?id=1092987241)
Changes made:
- styled the drag & drop file box to have a more approprate
**To Review:**
- start from a clean development installation of Rosalution and login as a user
``` bash
```
- Navigate to [local.rosalution.cgds/rosalution](local.rosalution.cgds/rosalution)
- Login as a user
- Click on any Analysis Card.
- hover over the vertical 3 dot menu and click on Attach
- switch over to the file attach section of the modal
- observer the following
=> Bug Fix: Input Dialog Box File Input Drag & Drop Area is too small height in height

frontend/src/components/AnnotationView/ImagesDataset.vue, frontend/src/components/SectionImage.vue, frontend/src/styles/main.css, frontend/src/views/AnnotationView.vue
Wrike Issue - [CSS improvements for fixing the annotation sidebar and row sizing](https://www.wrike.com/open.htm?id=1106354624)
- Fixed the sidebar to be sticky by setting a top value since it has a parent html element
- Adjusting image data set rows for section images so that they don't grow beyond the width of the browser page but will shrink when the page shrinks, doing this using flexbox
**To Review:**
- start from a clean development installation of Rosalution and login as a user
```bash
```
- Navigate to [local.rosalution.cgds/rosalution](http://local.rosalution.cgds/rosalution)
- Login as a user
- Click on any Analysis Card that has genomic units in it
- Choose any of the genes or variants and attach …
=> Css improvements sidebar and sizing

backend/tests/integration/test_analysis_routers.py, backend/tests/unit/core/test_annotate.py, backend/tests/unit/repository/test_annotation_collection.py, etc/fixtures/initial-seed/annotations-config.json
This is the annotation data part of updating the animal models from Alliance Genome.
[https://www.wrike.com/open.htm?id=1112499160](https://www.wrike.com/open.htm?id=1112499160)
[https://www.wrike.com/open.htm?id=1112498242](https://www.wrike.com/open.htm?id=1112498242)
Changes made:
- Provided a fix the jq 'attribute' portion for each animal gene identifier
- The previous jq attribute pulled the incorrect identifier
- Added new annotation configurations to pull the models for the following species:
- Rat (Rno)
- Mouse (Mmu)
- Zebrafish (Dre)
- Cel-elegens (Cel)
**To Review:**
``` bash
```
- Go to [http://local.rosalution.cgds/rosalution/](http://local.rosalution.cgds/rosalution/)
- …
=> Update Annotation Configuration to include new annotations from Alliance Genome

etc/fixtures/migrations/migrate-additional-sections.js
Wrike Ticket- [Create a migration script to update the data layer for the additional sections in the analysis that are within presentations as of Spring 2023](https://www.wrike.com/open.htm?id=1112510444)
Changes made:
-Wrote a migration script to update the analysis with the additional sections in the annotations. 
**To Review:**
- Switch to the `migration-script-additional-sections` branch
````bash
````
- Navigate to `http://local.rosalution.cgds/rosalution` and login with `developer`
- Click on the `CPAM0002` card and then the `VMA21` gene at the top of the AnalysisView
- Scroll to any of the AnnotationSections titled `Modelability` and `Protein Expression` and attach an image
- Run the migration script to rename the old …
=> Migration script to update the data layer for the additional sections

backend/tests/unit/repository/test_genomic_unit_collection.py, etc/fixtures/initial-seed/genomic-units.json
[https://www.wrike.com/open.htm?id=1131312019](https://www.wrike.com/open.htm?id=1131312019)
Changes made:
- Updated the fixtures for CPAM0084, now properly has genomic units imported when running docker build
**To Review:**
``` bash
docker-compose up --build
```
- Go to `http://local.rosalution.cgds/rosalution`
- Click on CPAM0084
- Click on either DLG4 or G6PD gene link
- Do annotations show up for DLG4 and G6PD?
=> Investigate why CPAM0084 breaks when re-running annotation from the api docs

frontend/src/components/AnalysisListing/AnalysisListingLegend.vue, frontend/src/views/AnalysisListingView.vue, frontend/test/components/AnalysisListing/AnalysisListingLegend.spec.js, frontend/test/views/AnalysisListingView.spec.js, system-tests/e2e/status_filter_case_cards.cy.js
Wrike Task- [As an authorized user, I want to filter by status rollup so that I can quickly find cases within the application based on this criteria.](https://www.wrike.com/open.htm?id=1079629899)
Changes made:
- Made the statuses in the legend clickable
- when clicking on a status, it will filter all other cases out that do not have that status
- added CSS properties to indicate the active or inactive state of that status
-Added tests for this feature 
**To Review:**
1.   Deploy Rosalution
``` bash
``` 
2. Go to: [http://local.rosalution.cgds/rosalution/](http://local.rosalution.cgds/rosalution/)
3. Login with a user
- username: developer
4. click on a status in the legend to filter out all other statuses. …
=> Status rollup filter

backend/README.md, backend/tests/unit/core/test_annotation_task.py
Due to changes, the ROSALUTION_KEY environment variable is no longer set in bash_rc/zprofile. It needs to be set somewhere to run the backend tests, so it is manually set when pytests are run.
[https://www.wrike.com/open.htm?id=1152723696](https://www.wrike.com/open.htm?id=1152723696)
Changes made:
- Updated the backend documentation to explain why the key is needed to be defined when running pytest.
- Updated each pytest to include a fake key to run the tests
**To Review:**
``` bash
cd backend
source rosalution_env/bin/activate
ROSALUTION_KEY="fake-rosalution-key-used-in-pytest" pytest -s tests/unit
ROSALUTION_KEY="fake-rosalution-key-used-in-pytest" pytest -s tests/integration
ROSALUTION_KEY="fake-rosalution-key-used-in-pytest" pytest --cov=src --cov-fail-under=80 --cov-branch …
```
=> Update the backend documentation to describe how to run pytest with a manual ROSALUTION_KEY environment variable

backend/src/core/phenotips_importer.py, backend/src/routers/analysis_router.py, backend/tests/unit/core/test_phenotips_importer.py, etc/fixtures/initial-seed/analyses.json, etc/fixtures/migrations/migrate-new-sections-phenotips-importer.js, frontend/src/components/AnalysisView/SectionBox.vue, frontend/src/components/AnalysisView/SectionText.vue, system-tests/e2e/attach_analysis_section_image.cy.js, system-tests/e2e/edit_case_analysis.cy.js, system-tests/e2e/view_collapsible_case_information.cy.js
Wrike Tickets - [Update the phenotips importer to create new sections that are needed from  presentations as of Spring 2023](https://www.wrike.com/open.htm?id=1112501989)
[As a clinical researcher, I need a place to enter information regarding each gene's molecular mechanism data per gene in a case](https://www.wrike.com/open.htm?id=1112500777)
Changes made:
- Updated the sections in the "backend/src/core/phenotips_importer.py" to reflect the analysis section.
- Crafted a migration script to migrate the old cases to the new structure (move data to different sections and create new sections)
**To Review:**
1. Download the archived production database to your local machine.  See @SeriousHorncat for the URL to download it from Box.
2. Import the …
=> Phenotips importer update and corresponding Migration Script

frontend/src/components/AnalysisListing/AnalysisCard.vue, frontend/src/components/RosalutionHeader.vue, frontend/src/components/SectionImage.vue
Wrike Ticket - [Monday.com, Phenotips, and Rosalution temporary Icons are broken on Production (BUG)](https://www.wrike.com/open.htm?id=1183837287)
Changes made:
- @JmScherer Fixed the assets for the 3rd party link attachments and the temporary loading image from being broken links
**To Review:**
It is very important to note ** must run branch __resolve-assets-missing-from-production-local-test-branch__ because the changes to disable packaging and stripping loggin has to be temporarily removed so that we can login locally for production **
``` bash
git checkout resolve-assets-missing-from-production-local-test-branch
docker-compose -f docker-compose.local-production.yml up --build
```
- Go to …
=> Image assets in production with broken links

frontend/src/components/SectionImage.vue, frontend/src/main.js, frontend/src/views/FileView.vue, system-tests/e2e/attach_analysis_section_image.cy.js
Wrike Ticket - [Investigate how to improve the images and how we expect them to work in the application](https://www.wrike.com/open.htm?id=1184833307)
Changes made:
- Removed the 'in focus' lightbox effectively and opens the image in a new 'file view' with it at full resolution
**To Review:**
``` bash
```
- Go to http://local.rosalution.cgds/rosalution/
- Login with `vrr-prep` user
- Upload images on analysis and annotation sections
- Images on left click or "right click and open in new window" allow it to open more naturally?
=> Opening images in new tab for the short term

backend/src/core/phenotips_importer.py, etc/fixtures/initial-seed/analyses.json
Wrike Ticket - [Add ACMG fields to Brief](https://www.wrike.com/open.htm?id=1200204518)
Changes made:
- Added ACMG fields to be in the brief section and Decision also when creating a case
**To Review:**
``` bash
```
- Import any valid case
- Open the case and verify the new fields appear as expected in the brief section
-   ![Screenshot 2023-09-13 at 8 53 21 AM](https://github.com/uab-cgds-worthey/rosalution/assets/1209059/80f78bc3-110c-47ba-85e2-7338f55daa89)
=> Updated the importer to include the new ACMG expected fields 

.github/workflows/system-tests.yml
Changes made:
- Updated the `system-tests.yml` to use `electron` instead of `chrome`
**To Review:**
=> Updated the system tests workflow to use electron

backend/src/models/analysis.py, etc/fixtures/initial-seed/analyses.json, frontend/src/models/analyses.js
Wrike Ticket - [[Backend] Update backend structure to handle storing a discussion post in the Analysis](https://www.wrike.com/open.htm?id=1206942378)
Changes made:
- Updated the fixtures and model for an analysis to include posts for a discussions with existing users in the system. Following MongoDB's recommendations, instead of embedding and referencing the user by a unique identifier or ObjectId, am directly saving the author's full name within each post.
**To Review:**
``` bash
```
1. Go to http://local.rosalution.cgds/rosalution/
2. Login with developer
3. Choose an analysis on the listing
4. Inspect the network traffic for the analysis and see discussions as a …
=> Created a discussions property for analyses

backend/src/repository/analysis_collection.py, backend/src/routers/analysis_router.py, backend/tests/fixtures/analysis-CPAM0002.json, backend/tests/fixtures/empty-pedigree.json, backend/tests/unit/repository/test_analysis_collection.py, etc/fixtures/initial-seed/analyses.json, etc/fixtures/migrations/migrate-insert-animal-model-systems.js
[https://www.wrike.com/open.htm?id=1233370000](https://www.wrike.com/open.htm?id=1233370000)
Changes made:
- Added endpoints to attach either a file or link to a section field in an analysis
- Added endpoints to remove file or link from sections fields in an analysis
**To Review:**
``` bash
<docker stuff here>
```
Section File Attach Endpoint Submission
**Section File Attach Endpoint Response**
**Section Link Attach Endpoint Submission**
**Section Link Attach Endpoint Response**
**Analysis Animal Model Evidence Fields**
**Section File Remove Endpoint Submission**
**Section File Remove Endpoint Response**
**Analysis Animal Model File Removal Result**
**Section Link Remove Endpoint Submission**
**Section Link Remove Endpoint Response**
**Analysis …
=> Animal model section backend

backend/src/repository/analysis_collection.py, frontend/src/views/AnalysisView.vue, frontend/test/views/AnalysisView.spec.js
Wrike Ticket - [Create new row item analysis view component to attach a supporting evidence attachment](https://www.wrike.com/open.htm?id=1233370000)
Changes made:
- Resolved issue due to an incorrect assumption on what parts of the request to use to update the view.
- 
**To Review:**
``` bash
```
- Update VMA21 CPAM 0002 case to include attachments for the animal modeling supporting evidence fields
=> Animal models updates page correctly

.gitignore
Changes made:
- Updated the .gitignore to include the `./etc/.certificates` folder
**To Review:**
``` bash
./setup.sh clean
```
- Go to `local.rosalution.cgds/rosalution` does it give a security error?
- Look at `git status` is anything changed? It should NOT include the .pem files
**The .pem files are grey in your vscode indicating that they are not included in git commits**
=> Make sure Rosalution is properly ignoring the self signed certificates generated by mkcert

frontend/src/components/AnalysisView/DiscussionSection.vue, frontend/src/styles/rosalution.css, frontend/test/components/AnalysisView/DiscussionPost.spec.js, frontend/test/components/AnalysisView/DiscussionSection.spec.js, system-tests/e2e/discussions_analysis.cy.js
[https://www.wrike.com/open.htm?id=1206938761](https://www.wrike.com/open.htm?id=1206938761)
**Changes made:**
- Clicking the "New Discussion" button opens a new field below the line
- Publishing a post closes the "New Discussion" field and clears the new post text input
- Still performs the expected emit to publish the post
- If there is no text in the input field, the publish button is disabled
- Cancelling a post closes the "New Discussion" field and clears the new post text input
- Updated Frontend unit tests and System tests to reflect the changes
- The Discussion Section Frontend unit tests updated to use chai
- Updated the CSS to be closer to the Figma design
**To Review:**
``` bash …
```
=> [Frontend] Clicking the "New Discussion" button opens a field below the header line divider to enter an opinion

backend/src/repository/analysis_collection.py, backend/src/routers/analysis_discussion_router.py, backend/tests/fixtures/analysis-CPAM0002.json, backend/tests/fixtures/empty-pedigree.json, backend/tests/integration/test_analysis_routers.py, backend/tests/unit/repository/test_analysis_collection.py
[https://www.wrike.com/open.htm?id=1207696914](https://www.wrike.com/open.htm?id=1207696914)
Changes made:
- Added a new Analysis Collection function to append a new post to the analysis discussion section
- Added unit and integration tests
**To Review:**
``` bash
docker compose up --build  
```
- Go to [https://local.rosalution.cgds/rosalution](https://local.rosalution.cgds/rosalution)
- Click on `CPAM0002`
- Click on the `Discussion` button in the shortcut links or scroll to the `Discussion` section
- Add multiple posts
---
=> [Backend] Add a new route and repository to handle an incoming post and save it in Mongo

backend/src/core/phenotips_importer.py, etc/fixtures/initial-seed/analyses.json
[https://www.wrike.com/open.htm?id=1206943181](https://www.wrike.com/open.htm?id=1206943181)
Changes made:
This pull request is intended to create consistency with how Analysis documents are created
- Updates the `PhenotipsImporter.py` to add both the `discussions` and `supporting_evidence_files` keys to every uploaded analysis.
- Assigns to empty arrays
- Updates the existing fixtures to include the keys
- Consistent fixture data to have empty arrays if no entries
**To Review:**
``` bash
```
- Go to [http://local.rosalution.cgds/rosalution](http://local.rosalution.cgds/rosalution)
- Click on the card with the `+`
- Upload a new analysis …
=> [Backend] Update the importer to include adding a discussion section in each new analysis

backend/src/models/user.py, frontend/src/components/AnalysisView/DiscussionPost.vue, frontend/src/components/AnalysisView/DiscussionSection.vue, frontend/src/components/ContextMenu.vue, frontend/src/components/RosalutionHeader.vue, frontend/src/main.js, frontend/src/stores/authStore.js, frontend/src/views/AnalysisView.vue, frontend/test/components/AnalysisView/DiscussionPost.spec.js, frontend/test/components/AnalysisView/DiscussionSection.spec.js, frontend/test/components/RosalutionHeader.spec.js, frontend/test/stores/authStore.spec.js
[https://www.wrike.com/open.htm?id=1221575483](https://www.wrike.com/open.htm?id=1221575483)
Changes made:
- Include a triple dot context menu button on each discussion post
- Only a user who posted that item will be able to see/interact with the context menu of that post
- Buttons in the context menu to either Edit or Delete a post
- Add a 'Hamburger'-style menu button and replace the existing action menu in the Rosalution Header
**To Review:**
``` bash
```
- Go to: [https://local.rosalution.cgds/rosalution](https://local.rosalution.cgds/rosalution)
- Login as `developer`
- Click on the `CPAM0002` analysis card
- Does the context menu work?
- Click on edit, does it …
=> Adding context menu to discussion posts

backend/src/models/analysis.py, backend/src/repository/analysis_collection.py, backend/src/routers/analysis_discussion_router.py, backend/tests/integration/conftest.py, backend/tests/integration/test_analysis_routers.py, backend/tests/unit/models/test_analysis.py, backend/tests/unit/repository/test_analysis_collection.py
[[Backend] Remove and edit post route and methods to update and delete a post from the discussion section](https://www.wrike.com/open.htm?id=1221584146)
Changes made:
This pull request adds the routes to edit and delete discussion posts in an analysis discussion section.
**Get Analysis Discussion Get Route**
- @router.get("/{analysis_name}/discussions")
- analysis_name
**Edit Analysis Discussion Post Route**
- @router.put("/{analysis_name}/disussions/{discussion_post_id}")
- analysis_name
- client_id
**Delete Analysis Discussion Post Route**
- @router.delete("/{analysis_name}/discussions/{discussion_post_id}")
- analysis_name
- client_id
---
**To Review:**
``` bash …
```
=> [Backend] Remove and edit post route and methods to update and delete a post from the discussion section

frontend/src/components/AnalysisView/DiscussionPost.vue, frontend/src/components/AnalysisView/DiscussionSection.vue, frontend/src/components/ContextMenu.vue, frontend/src/models/analyses.js, frontend/src/requests.js, frontend/src/views/AnalysisView.vue, frontend/test/components/AnalysisView/DiscussionPost.spec.js, frontend/test/components/AnalysisView/DiscussionSection.spec.js, frontend/test/components/RosalutionHeader.spec.js, frontend/test/models/analyses.spec.js, frontend/test/views/AnalysisView.spec.js, system-tests/e2e/discussions_analysis.cy.js
[https://www.wrike.com/open.htm?id=1264660177](https://www.wrike.com/open.htm?id=1264660177)
Changes made:
- The Delete button in the context menu calls the route and sends the analysisName and postId to be deleted
- The Delete option will display a confirmation dialog modal asking if the user is sure they want to delete the post
- System Tests for deleting action
- Successful Delete
- Cancelled Delete
**To Review:**
``` bash
```
- Go to [https://local.rosalution.cgds/rosalution](https://local.rosalution.cgds/rosalution)
- Click on `CPAM0002` card
- Scroll to the `Discussions` section
- Click on the `...` context menu for the post
- Select …
=> [Frontend] The vertical '...' context menu functions to delete posts

frontend/src/components/AnalysisView/DiscussionPost.vue
Changes made:
- Changed the Discussion post string to reflect the user's current timezone
**To Review:**
``` bash
```
- Go to `local.rosalution.cgds/rosalution`
- Click a case card
- Scroll down to `Discussion` and click `New Post`
- Make a post
- Does it have the correct time you posted?
---
=> Updated the discussion post to show the correct time

backend/src/main.py
Wrike Ticket - [Investigate resolving the "Unverified HTTPS request warning' made to host](https://www.wrike.com/open.htm?id=1383710529)
Changes made:
- Disabling the warnings from urllib3 to avoid the logs being overloaded
**To Review:**
``` bash
```
1. Go to: https://local.rosalution.cgds/rosalution/
2. Login as 'developer'
3. In a terminal, follow the docker logs for the Rosalution backend service
```bash
docker logs --follow rosalution-backend-1
```
5. In browser in Rosalution, click 'Create New Analysis' card and import 'C-PAM0076.json' within the 'etc/fixtures/import'. and follow logs to see if the warning is visible.
6. In browser in Rosalution, click 'Create New …
=> Disable unnecessary warning urllib3

etc/fixtures/import/CILI_2_5K_ARMC9_L510V.json, etc/fixtures/migrations/migrate-cpam-to-ciliopathies-landing-page.js
[https://www.wrike.com/open.htm?id=1472359818](https://www.wrike.com/open.htm?id=1472359818)
Changes made:
- Added a new migration script `etc/fixtures/migrations/migrate-cpam-to-ciliopathies-landing-page.js` that will convert a CPAM analysis landing page to a Ciliopathies analysis landing page
- Added `etc/fixtures/import/CILI_2_5K_ARMC9_L510V.json` as an example Ciliopathies analysis to upload and test migration
**To Review:**
``` bash
```
- Go to `local.rosalution.cgds/rosalution`
- Login as `developer`
- Click on the `Create New Analysis` card
- Upload the analysis located at `etc/fixtures/import/CILI_2_5K_ARMC9_L510V.json`
```bash
docker exec -it …
```
=> Draft script to run on every Cilipathies case to update landing page with new sections and fields

.gitignore, CHANGELOG.md, backend/requirements.txt, backend/src/security/security.py, frontend/package.json, frontend/test/views/AnnotationView.spec.js, frontend/vite.config.js, frontend/yarn.lock
Wrike Ticket - [Resolve vulnerabilities from package dependencies and python bcrypt warning](https://www.wrike.com/open.htm?id=1503343742)
**Changes made:**
- Upgraded frontend 'sinon' package dependency -> _16.0.0 to 19.0.2_: to upgrade 'path-to-regexp' to 8.2.0
- Upgraded frontend 'vitest' package dependency -> _1.6.0 to 2.1.1_: to remove 'micromatch', implement major version upgrade to make easier for future vulnerability dependency release
- Upgraded frontend 'vite' package dependency  -> _'5.3.2' to '5.4.8'_: to resolve several vulnerabilities
- Upgraded frontend '@vitejs/plugin-vue' package dependency  -> _'5.0.5' to 5.1.4_
- Include changelog updates for 0.7.0 Rosalution
**Important Note**: Updates for resolving some of Vite's package dependencies are not released yet; but will be …
=> Vulnerability audit for 0.7.0 & Removal of passlib as dependency

CHANGELOG.md, backend/requirements.txt
Wrike Ticket - [[Chore] Upgrade jq python module to 1.8.0 for Python 3.13+ support](https://www.wrike.com/open.htm?id=1666690922)
Changes made:
- Upgraded jq Python module to 1.8.0 to build successfully with Python 3.13
**To Review:**
``` bash
./setup.sh clean
```
=> Upgrading jq package to 1.8.0 for jq to work with python 3.13
